apiVersion: v1
kind: Service
metadata:
  name: fin-service-deployment
spec:
  type: ClusterIP
  selector:
    app: fin-service-deployment
  ports:
    - name: service
      port: 3000
      protocol: TCP
      targetPort: 3000