steps:

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}', '/config']
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/$PROJECT_ID/ci-buildnum'
    args: ['/config/buildnum', '/config/.buildenv']
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/$PROJECT_ID/ci-build-deployment-logger'
    args: ['/config']
    env: 
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'
    - '_UCD_LIB_INITIATOR=$_UCD_LIB_INITIATOR'
    - '_GITHUB_EVENT=$_GITHUB_EVENT'
    - '_GITHUB_ISSUE_NUMBER=$_GITHUB_ISSUE_NUMBER'
    - '_GITHUB_REPOSITORY=$_GITHUB_REPOSITORY'
    - '_GITHUB_PR_USER=$_GITHUB_PR_USER'
    - '_GITHUB_PR_MERGED_BY=$_GITHUB_PR_MERGED_BY'
    - 'BUILD_ID=$BUILD_ID'
    - 'SHORT_SHA=$SHORT_SHA'
    - 'TAG_NAME=$TAG_NAME'
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/config/buildnum', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}/buildnum']
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '/config/${BUILD_ID}', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}/${BUILD_ID}']
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud compute instances start arm64-build-instance --zone=us-central1-a'

  # make sure the instance is up and running
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud compute instances describe arm64-build-instance --zone=us-central1-a --format="yaml(name,status)"'

  - name: 'gcr.io/cloud-builders/git'
    id: 'setup-ssh'
    secretEnv: ['ARM_BUILDER_SSH_KEY', 'ARM64_MACHINE_IP']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "writing key"
      echo "$$ARM_BUILDER_SSH_KEY" >> /root/.ssh/ci-bot
      echo "modifying key permissions"
      chmod 400 /root/.ssh/ci-bot
      echo "adding key to ssh agent"
      ssh-keyscan -t rsa $$ARM64_MACHINE_IP > /root/.ssh/known_hosts
      echo "ssh setup complete"
      sleep 60
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: gcr.io/cloud-builders/docker
    waitFor: ['setup-ssh']
    entrypoint: "bash"
    args: ["-c", "./devops/build-context.sh"]
    env: 
      - 'BUILD_ARCHITECTURE=amd'
      - 'GCLOUD_BUILD=true'
      - 'GIT_DISCOVERY_ACROSS_FILESYSTEM=1'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
    secretEnv: ['ARM64_MACHINE_IP']
    volumes:
    - name: 'config'
      path: '/config'
    - name: 'ssh'
      path: /root/.ssh
    timeout: 7200s

  - name: gcr.io/cloud-builders/docker
    waitFor: ['setup-ssh']
    entrypoint: "bash"
    args: ["-c", "./devops/build-context.sh"]
    env: 
      - 'BUILD_ARCHITECTURE=arm'
      - 'GCLOUD_BUILD=true'
      - 'GIT_DISCOVERY_ACROSS_FILESYSTEM=1'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
    secretEnv: ['ARM64_MACHINE_IP']
    volumes:
    - name: 'config'
      path: '/config'
    - name: 'ssh'
      path: /root/.ssh
    timeout: 7200s

  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["-c", "./devops/create-manifest.sh"]
    volumes:
    - name: 'config'
      path: '/config'  

options:
  pool:
    name: projects/digital-ucdavis-edu/locations/us-central1/workerPools/ucd-lib-arm-builds

availableSecrets:
  secretManager:
  - versionName: projects/digital-ucdavis-edu/secrets/arm64-builder-ci-bot-ssh-key/versions/latest
    env: 'ARM_BUILDER_SSH_KEY'
  - versionName: projects/digital-ucdavis-edu/secrets/arm64-builder-ip/versions/latest
    env: 'ARM64_MACHINE_IP'

substitutions:
  _CONFIG_BUCKET: ci-build-config
  _CONFIG_PROJECT: fin
  _UCD_LIB_INITIATOR: unknown
  _GITHUB_EVENT: ''
  _GITHUB_ISSUE_NUMBER: ''
  _GITHUB_REPOSITORY: ''
  _GITHUB_PR_USER: ''
  _GITHUB_PR_MERGED_BY: ''

timeout: 7200s