apiVersion: v1
kind: Service
metadata:
  name: fcrepo
spec:
  type: ClusterIP
  selector:
    app: fcrepo
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672