apiVersion: apps/v1
kind: Deployment
metadata:
  name: init
spec:
  selector:
    matchLabels:
      app: init
  template:
    metadata:
      labels:
        app: init
    spec:
      containers:
      - name: service
        image: gcr.io/ucdlib-pubreg/fin-init:sandbox
        env:
        - name: FIN_SERVICE_NAME
          value: "init"