apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: default
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: gcr.io/ucdlib-pubreg/fin-elastic-search:sandbox
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        env:
          - name: "ES_NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "ES_DISCOVERY_TYPE"
            value: "multi-node"
          - name: "ES_DISCOVERY_SEED_HOSTS"
            value: "elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch"
          - name: "ES_CLUSTER_INITIAL_MASTER_NODES"
            value: "elasticsearch-0,elasticsearch-1"
          - name: "ES_JAVA_OPTS"
            value: "-Xms1g -Xmx1g"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
