apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbsync
spec:
  selector:
    matchLabels:
      app: dbsync
  template:
    metadata:
      labels:
        app: dbsync
    spec:
      containers:
      - name: service
        command: ["npm"]
        args: ["run", "dbsync"]
        env:
        - name: FIN_SERVICE_NAME
          value: "dbsync"