apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: fin-service-deployment
    options:
      allowNameChange: true   
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: fin-service-deployment
      $patch: delete